image: Visual Studio 2017
environment:
    matrix:
        -   BOOST_MINOR: 65
        -   BOOST_MINOR: 64
install:
    -   ps: mkdir C:/ASIO-CARES
    -   ps: ./.appveyor/boost.ps1 $env:BOOST_MINOR
    -   ps: ./.appveyor/cares.ps1
build_script:
    -   mkdir build
    -   cd build
    -   ps: wget https://raw.githubusercontent.com/Kitware/CMake/e710d6953dae27f73452095df6d7b2d7ec698fd1/Modules/FindBoost.cmake -OutFile FindBoost.cmake
    -   ps: mv FindBoost.cmake ../cmake/modules
    -   ps: cmake .. -G "Visual Studio 15 2017 Win64" "-DBOOST_ROOT=C:/ASIO-CARES/boost_1_$($env:BOOST_MINOR)_0" "-DBOOST_INCLUDEDIR=C:/ASIO-CARES/boost_1_$($env:BOOST_MINOR)_0" "-DBOOST_LIBRARYDIR=C:/ASIO-CARES/boost_1_$($env:BOOST_MINOR)_0/stage/lib" -DBoost_USE_STATIC_LIBS=On "-DCMAKE_CXX_FLAGS=/D_WIN32_WINNT=0x0A00 /DWINVER=0x0A00 /EHsc" -DCARES_LIBRARY=C:/ASIO-CARES/c-ares-master/build/lib/Release/cares.lib -DCARES_INCLUDE_DIR=C:/ASIO-CARES/c-ares-master
    -   cmake --build . --config Release
test_script:
    -   ctest -VV -C Release
