/**
 *	\file
 */

#pragma once

#include <boost/system/error_code.hpp>

namespace asio_cares {

/**
 *	Creates a `boost::system::::error_code`
 *	object which represents an error code
 *	generated by libcares.
 *
 *	\param [in] code
 *		The error code from libcares.
 *
 *	\return
 *		A `boost::system::error_code` which
 *		wraps \em code.
 */
boost::system::error_code make_error_code (int code) noexcept;

/**
 *	Throws a `boost::system::system_error`
 *	wrapping the result of `make_error_code(code)`
 *	if and only if \em code is not `ARES_SUCCESS`.
 *
 *	\param [in] code
 *		The error code from libcares.
 */
void raise (int code);

}
